### ISSUE TITLE
如何设置button中的文字居左

### ISSUE THREAD

**Issue by chenwuwen** [ansnail/SuperButton#5]
如题，文字默认是居中的，但是无法居左或者局右，调用android:textAlignment 、android:gravity都没有效果

**Comment by ansnail** [comment]
你好，文字暂时不支持居左或者居右显示哈

**Comment by chenwuwen** [comment]
这个在未来的考虑范围内吗？非常易用的一款组件，文字位置不能调整的话，真的十分遗憾，如果工作忙，不能全身投入的话，我可以加入开发吗

**Comment by ansnail** [comment]
可以呀，你可以加入自己需要的属性，然后提meger request就好了，不过需要注意下，
1.minSdkVersion支持到16
2.符合易用的风格
其余随意啦
